spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 192.168.66.134
server:
  port: 9009
aliyun:
  sms:
    accessKeyId: LTAIG3ZBaWeDg49D
    accessKeySecret: CZEjPtmIGT44A1PlLTY0uhztQf9gBC
    template_code: SMS_142616397
    sign_name: 练宏