server:
  port: 9010
spring:
  application:
    name: tensquare_friend #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.66.134:3306/tensquare_friend?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.66.134
  redis:
    host: 192.168.66.134
jwt:
  config:
    key: dlms
    ttl: 6000000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true #配置之后以后在服务器部署的时候可以跨域访问,本地测试可以不加
